### ISSUE TITLE
Can this be removed?

### ISSUE THREAD

**Issue by kenman345** [ROMaster2/LiveSplit.VideoAutoSplit#26]
I was looking over some code and noticed this nested if statement at the end of an if statement for the same condition. Unless I am missing something about that property being changes with the first part, then this can easily be removed so we dont test a condition that will always be true and instead just go right into doing things.
https://github.com/ROMaster2/LiveSplit.VideoAutoSplit/blob/f4ebcce0e02b510b261cf0ebe9b6752ff9820de5/VASL/VASLScript.cs#L147

**Comment by kenman345** [comment]
also, do we not have an else statement for that section? Is that a miss or by design? Still digging into the code

**Comment by ROMaster2** [comment]
You are correct, nice catch. It's meant to be used if there's a gameTime method defined in the script.

Added in https://github.com/ROMaster2/LiveSplit.VideoAutoSplit/commit/90d2d4a625bb5c2c01c4f450fdc9cde779eb7d68
