### ISSUE TITLE
Still getting NaNs?

### ISSUE THREAD

**Issue by kenman345** [ROMaster2/LiveSplit.VideoAutoSplit#28]
Noticed this and wanted to see if the NaNs still occur or have been fixed. Also, now we have an issue open for it if its still happening.

https://github.com/ROMaster2/LiveSplit.VideoAutoSplit/blob/f4ebcce0e02b510b261cf0ebe9b6752ff9820de5/Scanner.cs#L531

**Comment by ROMaster2** [comment]
It happens when the history is empty.

Changed the comment in https://github.com/ROMaster2/LiveSplit.VideoAutoSplit/commit/4e930dec1566a56d849628a85c9b74c832c75ca9, but there may still be a better way to write that.

**Comment by kenman345** [comment]
Yea, then lets close this since the comment makes sense and looking it over, I have not found any way around it. We have a history where we have only blanks, so the code never increments that variable. 

Closing this
